spring:
  application:
    name: ljfl
  profiles:
    active: @deployType@
    #active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      #最大文件上传量
      max-file-size: 200MB
      #文件请求最大量
      max-request-size: 200MB
  freemarker:
    check-template-location: false
server:
  port: 8080
  servlet:
    context-path: /order-api
  max-http-header-size: 4048576
logging:
  config: classpath:logback-spring.xml