package com.dxhy.order.dao;

import com.dxhy.order.model.OrderItemInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderItemInfoMapper {

    int deleteByPrimaryKey(String id);
    
    /**
     * 根据orderId删除明细数据表
     *
     * @param orderId
     * @return
     */
    int deleteOrderItemInfoByOrderId(@Param("orderId") String orderId);

    /**
     * This METHOD was generated by MyBatis Generator.
     * This METHOD corresponds to the database table order_item_info
     *
     * @mbggenerated
     */
    int insertOrderItemInfo(OrderItemInfo record);

    /**
     * This METHOD was generated by MyBatis Generator.
     * This METHOD corresponds to the database table order_item_info
     *
     * @mbggenerated
     */
    OrderItemInfo selectByPrimaryKey(String id);
    
    /**
     * 根据订单id查询订单明细
     * @param orderId
     * @return
     */
    List<OrderItemInfo> selectOrderItemInfoByOrderId(String orderId);

    List<OrderItemInfo> selectAllByOrderId(List<String> orderInfoIdList);

    /**
     * @param @param  resultOrderItemList
     * @param @return
     * @return int
     * @throws
     * @Title : insertOrderItemByList(这里用一句话描述这个方法的作用)
     * @Description ：批量插入orderItem表
     */

    int insertOrderItemByList(@Param("list") List<OrderItemInfo> resultOrderItemList);
    
}
